import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import Footer from "../components/global/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links: Array<{ href: string; key: string }> = [
  {
    href: "/",
    key: "home",
  },
  {
    href: "/signUp",
    key: "signUp",
  },

  {
    href: "/login",
    key: "login",
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <header>
        <div>
          <ul className="flex bg-slate-500">
            {links.map(({ href, key }) => (
                <li className="flex-auto">
                  <Link href={href} key={key}>
                    {key}
                  </Link>
                </li>
            ))}
          </ul>
        </div>
      </header>
    {children}
    {/*<Footer />*/}
    </body>

    </html>
  )
}
